# Generated by Django 3.2b1 on 2021-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='start_date',
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
